# เครดิตความรู้ดีจาก เพจ Datawiz 
https://www.facebook.com/datawizthailand/

ในการสร้าง numpy array input ที่เข้ามาจะต้องเป็น list เท่านั้นเราสามารถทำ nested loop เพื่อสร้าง list เป็น array หลายมิติได้เเละเราสามารถกำหนด data type ของ array ได้โดยกำหนด parameter ใน function dtype()

# สร้าง Vector , Metric 

In [1]:
import numpy as np 
from IPython.display import display 

สร้าง vector (array 1 มิติ)

In [8]:
vector = np.array([1,2,3],dtype = 'int8')

In [9]:
vector

array([1, 2, 3], dtype=int8)

เช็ค dimension ของ array การเช็ค dimension ของ numpy array สามารถทำได้ด้วย property .shape จะ return ค่าเป็นขนาดของ list ที่อยู่ด้านนอกที่สุด ไล่เข้าไปข้างใน (กรณี matrix 2 มิติ ก็มองว่าเป็น list ซ้อน list โดยจำนวน list ที่ซ้อนอยู่ข้างในทั้งหมด คือ จำนวน row และ จำนวน element ของ list ที่ซ้อนอยู่ คือ จำนวน column)

In [10]:
vector.shape 

(3,)

สร้าง metric (array ถูกสร้างมาหลายมิติ)

In [7]:
metric = np.array([[1,2,3],[4,5,6]],dtype ='float64')
metric

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
metric.shape

(2, 3)

คำสั่งเรียก array ชนิดพิเศษบางชนิด 

In [12]:
display(np.ones([3,3]));

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
display(np.zeros([3,3]));

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Indexing

การระบุ index ของ numpy array ทำได้ไม่ยากโดยระบุ index ของแต่ละ dimension เข้าไปตามลำดับในวงเล็บ [] และอย่าลืมว่าการระบุ index ใน Python จะเริ่มจาก 0 และ index -1 จะหมายถึง element สุดท้าย

In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ระบุถึง 1 dimension 

In [17]:
display(a[0])

array([1, 2, 3])

In [18]:
display(a[1])

array([4, 5, 6])

In [19]:
display(a[-1])

array([7, 8, 9])

ระบุถึง 2 dimension 

In [20]:
display(a[1,1]);display(a[-1,-1])


5

9

ระบุ dimension โดยใช้ " : "

In [21]:
display(a[1:])

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
display(a[:,:-1])

array([[1, 2],
       [4, 5],
       [7, 8]])

ระบุหลาย index

In [24]:
display(a[[1,-1],:]);

array([[4, 5, 6],
       [7, 8, 9]])

In [25]:
display(a[:,[1,-1]])

array([[2, 3],
       [5, 6],
       [8, 9]])

ในการทำ operation (+ - * /) ต่างๆกับ numpy array แบบ element wise ถ้า dimension ของ 2 array มีขนาดเท่ากันก็สามารถทำ operation แบบจับคู่ element ที่ตำแหน่งเดียวกันได้เลย

# Operation เเบบ element wise 

In [26]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [29]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

operation ระหว่าง array กับ array ที่ dimension เหมือนกัน

In [31]:
display(a+b); display(a-b);display(a*b);display(a/b)


array([[ 6,  8],
       [10, 12]])

array([[-4, -4],
       [-4, -4]])

array([[ 5, 12],
       [21, 32]])

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

operation ระหว่าง array กับ scalar 

หาก 2 array มีจำนวน dimension ไม่เท่ากัน แต่มีขนาด dimension ที่ match กัน เช่น a มีขนาด 3x3, b มีขนาด 1x3 จะเห็นว่า a กับ b มีขนาด column ที่ match กัน ถ้าเราเอา a+b จะได้ผลลัพธ์เป็น a ที่ทุก row ถูก + ด้วย b นั่นเอง

operation ระหว่าง array ที่ dimension ไม่เหมือนกัน - Broadcasting 

In [32]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
b=np.array([[1,2,3]])

In [34]:
display(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
display(b)

array([[1, 2, 3]])

In [36]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

# Operation เเบบ matrix

In [37]:
# กำหนด A เป็น matrix ขนาด 3 x 2 
A = np.array([[1,2],
             [3,4],
             [5,6]])

In [38]:
# กำหนด B เป็น matrix ขนาด 2 x 1 
B = np.array([[1],
             [5]])

In [39]:
# คูณ matrix A x B = ได้ matrix ผลลัพธ์ขนาด 3 x 1 
np.dot(A,B)

array([[11],
       [23],
       [35]])

การคูณ matrix แบบที่เราเรียนกันมาในคณิตศาสตร์ม.ปลาย ให้ใช้ method “dot” (จำนวน col ของ matrix แรก ต้อง match กับ จำนวน row ของ matrix หลัง)

หา determinant

In [41]:
display(np.linalg.det(a))

-9.51619735392994e-16

สามารถใช้หา determinant และ inverse ของ matrix ได้

หา inverse

In [42]:
display(np.linalg.inv(a))

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

numpy มี method ในการคำนวณค่าทางสถิติต่างๆ มากมาย ถ้าใช้ method เหล่านี้กับ array โดยตรงก็จะได้ค่า สถิติของตัวเลขทั้งหมดใน numpy array แต่ถ้าเราต้องการคำนวณค่าทางสถิติเฉพาะ row หรือ column ของ array ให้กำหนด axis ไปด้วย

*ค่าสถิติในแต่ละ row -> axis=1, ค่าสถิติในแต่ละ column -> axis=1,

# หาค่าทางสถิติต่างๆ

In [43]:
a=np.array([[1,3],
           [4,9],
           [7,1]])
display(a)

array([[1, 3],
       [4, 9],
       [7, 1]])

หาค่า min,max,mean,standard dev

In [44]:
print(f'min:{np.min(a)}')

min:1


In [46]:
print(f'max:{np.max(a)}')

max:9


In [47]:
print(f'mean:{np.mean(a)}')

mean:4.166666666666667


In [48]:
print(f'std:{np.std(a)}')

std:2.9674156357941426


หาค่า min ,max, mean, standard dev เเต่ละ row 

In [49]:
print(f'min:{np.min(a,axis=1)}\tmax:{np.max(a,axis=1)}\tmean:{np.mean(a,axis=1)}\tstd:{np.std(a,axis=1)}')

min:[1 4 1]	max:[3 9 7]	mean:[2.  6.5 4. ]	std:[1.  2.5 3. ]


หาค่า min,max,mean,standard dev เเต่ละ column

In [50]:
print(f'min:{np.min(a,axis=0)}\tmax:{np.max(a,axis=0)}\tmean:{np.mean(a,axis=0)}\tstd:{np.std(a,axis=0)}')

min:[1 1]	max:[7 9]	mean:[4.         4.33333333]	std:[2.44948974 3.39934634]


# Reshape

บางครั้งตอนเราทำ machine learning model training จำเป็นต้อง reshape ข้อมูลก่อนเข้า model ตามที่แต่ละ library กำหนด การเข้าใจการ reshape ของ numpy array จึงมีความสำคัญ

In [51]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
display(a)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
display(a.reshape(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [53]:
#(1,-1) หมายความว่ากี่ column ก็ได้ขอให้ 1 row 
display(a.reshape(1,-1))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Random

ใน numpy.random มีฟังก์ชั่นสำหรับสุ่มค่ามากมาย ซึ่งรู้ไว้มีประโยชน์กับการ shuffle ข้อมูล หรือสุ่มเลือกข้อมูล ตอนทำโมเดลแน่นอน!

เซตค่า seed เพื่อ random ให้ได้ค่าเดิม

In [54]:
np.random.seed(1)

สร้าง array ที่มีค่า random ค่าระหว่าง(0,1)

In [57]:
display(np.random.rand(3,2))

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02]])

สร้าง array ที่มีค่า random เเบบ normal distribution(mean=0,std=1)

In [58]:
display(np.random.randn(3,2))

array([[-0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ],
       [ 1.74481176, -0.7612069 ]])

สร้าง array ที่มีค่า random เเบบ normal distribution (mean=0,std=1)

In [59]:
display(np.random.randn(3,2))

array([[ 0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071],
       [-0.3224172 , -0.38405435]])

random ค่าจากใน list โดยกำหนดค่า probabability ของเเต่ละตัวได้

In [61]:
display(np.random.choice([3,'nay',7,'yay',11], p=[0.1,0.1,0.2,0.3,0.3]))

'11'